### ISSUE TITLE
📋 889 tool

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#109]
**Tasks**

Go-live steps:

- [x] Need ATO finalized
- [x] Secure URL [http://889.smartpay.gsa.gov/]
- [x] Implement URL
- [x] Get system SAM API key
  - [x] Need to designate system managers: Tri, Andrew & Mark -- will substitute John in for Mark later
  - [x] [Request](https://docs.google.com/document/d/1GH-pNnwmQcWbWb3Ukh2GY-6oiVxmaSUPr03CuKt3xC4/edit) temporary increase to personal API key (dynamic IPs are incompatible with current API -- at least for a system API key)
  ~~- [ ] Investigate possibility of putting 889 tool behind VPN -- whether that will require another ATO~~ [Unnecessary; we got increase API limits]
- [x] Talk to GCP admins about standing this up in their prod environment
- [x] Get prod instance of GCP
- [x] Push to prod env
- [x] Point new domain at GCP prod env.
- [x] Finalize UI
- [x] Usability testing
 
-----------------

After launch:
- [x] Conduct cross-team retro/reflection
- [ ] Provide feedback to GCP team
- [ ] Support GSA SmartPay program in having convos w/ SAM.gov re: increased API limits
- [ ] After launch, consider submitting the 889 Tool to the Periodic Table of Acquisition Innovations...they have an "[acquisition automations](https://www.fai.gov/periodic-table?utm_medium=email&utm_source=govdelivery)" section that would be a good fit
- [ ] Consider having OGP update [C-SCRM](https://insite.gsa.gov/employee-resources/acquisition-purchases-and-payments/acquisition-portal/acquisition-by-topic/cybersupply-chain-risk-management-cscrm) - they said the would in a demo. Point of contact: Stephen Carroll
- [ ] Consider a blog post 
- [ ] Consider a GSAIT Tech Talk

**Comment by JessicaMarine1** [comment]
@mark-meyer I created this "Task" ticket for you to track whatever is needed for the 889 tool ATO process. Please feel free to modify.

**Comment by vickimcfadden** [comment]
@A-L33 we might want to loop back to OGP, specifically Stephen Carroll, so they can update the C-SCRM insite page with 889 information!

**Comment by rebekahperillo** [comment]
@A-L33 Checking with management.

**Comment by rebekahperillo** [comment]
@A-L33 Erin gave the thumbs up, feel free to proceed.
