### ISSUE TITLE
📋 ATO for agile projects

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#110]
**Tasks**

- [x] Schedule ATO training with Bo (CISO)
- [x] Develop list of questions we'd like to ask Bo: https://docs.google.com/document/d/1y6Uw1Pc_4TEk9Iddyy8QRmezsf-wzd_lzNA2mJjMwLY/edit
- [x] Figure out what ATO / pen testing requirements apply to:
  - [ ] program site (static site)
  - [ ] training site

**Comment by JessicaMarine1** [comment]
Note: Tri indicated that because DS is the "owner" of all 3, the program site, training site & 889 tool can (and will) all fall under the same ATO. This is the desired result from the SmartPay program so that they only have one ATO to maintain.
