### ISSUE TITLE
📋 wiki

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#111]
**Tasks**

- [x] [Product framing](https://github.com/GSA/smartpay-website/wiki/Product-framing) [Note: this is only for the program site; need to determine where to house the training site product framing]
- [x] [User types](https://github.com/GSA/smartpay-website/wiki/GSA-SmartPay-User-Types)
- [x] [Content guide](https://github.com/GSA/smartpay-website/wiki/GSA-SmartPay%C2%AE-Program:--Style-Guide-for-the-Website-and-Training-Platform)
- [ ] Content audit

Note: Using https://github.com/DOI-ONRR/nrrd/wiki as a model.
