### ISSUE TITLE
📋 Procurement

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#112]
**Tasks**

- [x] Draft RFQ (contract type; funding; etc.)
  - [x] Get approval from COs
  - [x] Get approval from Dave Shea
  - [x] Get approval from Tiffany Hixson
- [x] Release RFI / draft RFQ to industry
  - [x] Post on GitHub
  - [x] Email to vendors (Vicki has list)
- [x] Review RFI Feedback
- [x] Finalize RFQ
- [x] Release RFQ
- [ ] Evaluate submissions
- [ ] Award
- [ ] Onboarding

**Comment by JessicaMarine1** [comment]
RFI timeline:
- Early March: Had rough draft done; tried working a-sync with Tri to add security requirements 
- 3/16, 3/22, 3/28: Met with Tri to try to iron out security requirements; at 3/28 meeting DS's concern about T&M came out for the first time
- 4/3: Met with DS to discuss contract types; Jessica offered to meet with him to discuss experience managing T&M contract at USTC
- 4/4: Ashley provided DS with T&M determination & finding doc
