### ISSUE TITLE
📋 SmartPay timeline

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#114]
**Tasks**

https://app.mural.co/t/gsa6/m/gsa6/1677770046677/a3c428441e119ec8002de85693654dfbe0c230b2?sender=u464f7810c8d7ba09bf708121
- [x] Add discovery milestones / deliverables
- [x] Add 889 milestones
- [x] Add program website milestones
- [x] Add training site milestones
- [x] Add procurement milestones
