### ISSUE TITLE
Launch Checklist | Program Site

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#297]
When it is time to launch the new program site, we'll need to:

- [x] Coordinate with search.gov to index production site
- [x] Ask cloud.gov pages how much time they need for the site launch governance process
- [x] Fill out Pages's [new site launch form](https://docs.google.com/forms/d/1ujDu9mUNmHuCG2Mx5JYFUaXthYrf304yMpBrGOEudMA/edit) with enough time for them to go through there governance process.
- [x] Create a ticket with GSA IT to move the domain record for smartpay.gov to point to cloud.gov pages
- [x] DNS changes

**Comment by JessicaMarine1** [comment]
Program site launched 10.5.2023 🚀🚀
