### ISSUE TITLE
Launch Checklist | 889 tool

### ISSUE THREAD

**Issue by JessicaMarine1** [GSA/smartpay-website#298]
When it is time to launch the 889 tool on cloud.gov, we'll need to:

- [x] Ensure production environment on cloud.gov is running and environment is properly set up (frontend uses prod api)
- [x] Ask cloud.gov pages how much time they need for the site launch governance process
- [x] Fill out Pages's [new site launch form](https://docs.google.com/forms/d/1ujDu9mUNmHuCG2Mx5JYFUaXthYrf304yMpBrGOEudMA/edit) with enough time for them to go through there governance process.
- [x] Create a ticket with GSA IT to move the domain record for 889.smartpay.gov to point to cloud.gov pages

**Comment by JessicaMarine1** [comment]
Launched 10/3 🚀
